### ISSUE TITLE
Distribution by npm or bower

### ISSUE THREAD

**Issue by llaville** [bnjmnhndrsn/select2-optgroup-select#7]
Hello,

Very nice plugin that help me a lot. 
I've just one question: is it possible to think to distribute it with npm or bower please ?

Laurent

**Comment by karam12** [comment]
Have you tried :
`bower install bnjmnhndrsn/select2-optgroup-select` ?

**Comment by bnjmnhndrsn** [comment]
`npm install git://github.com/bnjmnhndrsn/select2-optgroup-select.git#0.0.7` should work too (or at least it works for us). You can add it to a package.json with that url too. You can do the versioning via the hash at the end. I will also look into setting up the package on NPM sometime this week.

By the way, thank you for using it!
